### ISSUE TITLE
[Note] AWS IRSA Roles

### ISSUE THREAD

**Issue by bryantbiggs** [particuleio/terraform-kubernetes-addons#1036]
Neither an issue nor a feature request, more of a PSA 😅 

I see that the https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-assumable-role-with-oidc module is used quite a bit for providing addons permissions via IRSA which is great. I just wanted to also point out that we have added a number of "canned" IRSA roles for common addons as well in https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks#iam-role-for-service-accounts-in-eks

Check it out if you get a chance, it may or may not be worthwhile. We have see great traction since we've added and more are getting added all the time. We are also seeing interactions with the community addons to push for better permissions that are more narrowly scoped which has been great as well. Thats all - great work, carry on, and feel free to close this out at any time since theres no action required!

**Comment by ArchiFleKs** [comment]
Hi @bryantbiggs thanks a lot for taking the time to post this, really appreciate it. 

I saw the new modules and started thinking about how to integrate them in this module. At first I tried with the [eks-role](https://github.com/particuleio/terraform-kubernetes-addons/pull/841) but had some downside because of the inability to specify the `number_of_role_policy_arns` I had a lot of issue with the classic "planning before apply" with the new module that I did not have with the OIDC one (thanks to the number variable).

I saw the eks addons centric module, which is great, and could offload a lot of the IAM complexity of this module to the upstream one. 

The only downside I see is that in this module we try to offer sensible defaults for common addons/tooling deployed on top of kube but we also want to let people be able to override policy. That's why you can see an [`iam_policy_override`](https://github.com/particuleio/terraform-kubernetes-addons/blob/main/modules/aws/aws-ebs-csi-driver.tf#L20) in almost every addons that make use of  of IRSA.

For example if people wants to restrict externalDns or certificate manager to a specific route53 zone for example, I wonder how this could be made available in the upstream module (maybe by allowing to use an existing policy to override the default module one, which could be created outside the module).

I'd be happy to contribute, I have just been lacking a bit of time at the moment to enhanced this module and refactor it to use the upstream one. I'm happy to hear your recommendations of you have any.

**Comment by ArchiFleKs** [comment]
I think they will all be feasible but might require a few PR, right now I'm thinking about aws-ebs-csi driver. Where we try to enforce default volume encryption and managing KMS key in this module, so we would need to be able to pass a KMS key to the upstream one. Anyway, nothing impossible.

**Comment by bryantbiggs** [comment]
It is already planned to remove the use of [`toset()`](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2113ea9a06e19e6993bebcbe51f7e2f3830f5842/modules/iam-role-for-service-accounts-eks/main.tf#L50) at the next major version release which is causing some poor usability issues https://github.com/terraform-aws-modules/terraform-aws-iam/issues/193 so hopefully that will help a bit 

Regarding the overriding and scoping of policies - the current approach we have taken is that the policy is defined as is, but we are providing variables that default to permissive values that "work out of the box" but still afford users the ability to restrict to their use case https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2113ea9a06e19e6993bebcbe51f7e2f3830f5842/modules/iam-role-for-service-accounts-eks/variables.tf#L133

But thank you for the feedback - even if you decide to not use them, I think feedback alone on the functionality provide is very helpful from various perspectives

**Comment by bryantbiggs** [comment]
Closing for now - more of just an FYI and thanks for sharing your use cases!
