### ISSUE TITLE
[thanos] tls values key for chart version 8.x

### ISSUE THREAD

**Issue by wyrie** [particuleio/terraform-kubernetes-addons#779]
It looks like the values key `grpcTLS` has been deprecated. See:
https://github.com/bitnami/charts/tree/master/bitnami/thanos/#to-800

https://github.com/particuleio/terraform-kubernetes-addons/blob/6db7dd7590755a7cccf124cb529b8b21e9959c46/modules/aws/thanos-tls-querier.tf#L39

**Comment by ArchiFleKs** [comment]
I needed to fix this here https://github.com/bitnami/charts/issues/8172 but never got around to it :/ for now I'm using the charts in version <8

**Comment by ArchiFleKs** [comment]
This is fixed  [here](https://github.com/particuleio/terraform-kubernetes-addons/commit/16b7057c13ed2149a6a4bfaa916b50fd0035a688) in [latest release](https://github.com/particuleio/terraform-kubernetes-addons/releases/tag/v3.0.0)

The default CA verification is let's encrypt R3 (The CA used on nginx publishing the thanos query TLS endpoint)  but please use the newly added variable to verify against your own CA PEM file [here](https://github.com/particuleio/terraform-kubernetes-addons/blob/main/modules/aws/thanos-tls-querier.tf#L14).

This is a bit of a workaround since upstream bug seems to have a lot of ramification since chart refactor and bitnami closes issue real quick. Not sur it is going to be fixed upstream and I don't have the time to do an upstream PR.

On the bright side, this adds a layer of security by doing server CA verification from the TLS querier.
