### ISSUE TITLE
[enhancement] create an option to setup prometheus monitoring using managed aws prometheus

### ISSUE THREAD

**Issue by mentos1386** [particuleio/terraform-kubernetes-addons#83]
**Is your feature request related to a problem? Please describe.**
I would like to use https://aws.amazon.com/prometheus/ instead of Thanos for long term storage.

**Describe the solution you'd like**
Would be nice if i could just write `use_managed_prometheus = true` and everything would be done behind the scene.

**Describe alternatives you've considered**
Setting it up myself, which i will do, but would rather have this module to also provision this for me.

**Additional context**
https://aws.amazon.com/blogs/mt/getting-started-amazon-managed-service-for-prometheus/

**Comment by ArchiFleKs** [comment]
This should be available soon. Everything seem to work but I get : 
```
Templating
Template variable service failed When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/workspaces/ws-8f395094-2502-4a8f-846a-ee1aeab12534/api/v1/series?end=1617994733&match%5B%5D=node_cpu_seconds_total&start=1617991133'
```

With Kubernetes default dashboard because the templating variable are failing. But I can still query metrics from the Explore pannel in grafana so I don't think this is related to sigv4 because I can remote write the metrics and I can see them in Grafana.

If you faced similar issue @mentos1386 let me know
